services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: securepipe-lite:compose

    container_name: securepipe-compose

    env_file:
      - .env

    ports:
      - "8000:8000"

    restart: unless-stopped