name: SecurePipe CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Download source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Secret scan with Gitleaks
        uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Semgrep
        run: pipx install semgrep

      - name: SAST scan with Semgrep
        run: semgrep scan --config auto --error

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"

      - name: Install pip-audit
        run: python -m pip install pip-audit==2.10.1

      - name: Audit Python dependencies
        run: pip-audit --no-deps -r requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check Python files
        run: python -m compileall app

      - name: Run automated tests
        run: python -m pytest -v

      - name: Verify FastAPI application
        run: python -c "from app.main import app; print('SecurePipe application loaded successfully')"

      - name: Build Docker image
        run: docker build -t securepipe-lite:ci .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: 'securepipe-lite:ci'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          scanners: 'vuln'
          skip-files: '**/pip/_vendor/bom.cdx.json'
          version: 'v0.74.0'

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin      

      - name: Push Docker image to GHCR
        if: github.event_name == 'push'
        run: |
          docker tag securepipe-lite:ci ghcr.io/${{ github.repository_owner }}/securepipe-lite:latest
          docker tag securepipe-lite:ci ghcr.io/${{ github.repository_owner }}/securepipe-lite:${{ github.sha }}

          docker push ghcr.io/${{ github.repository_owner }}/securepipe-lite:latest
          docker push ghcr.io/${{ github.repository_owner }}/securepipe-lite:${{ github.sha }}

